// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcZLKLC3g7fEvTd2R8HW4niPvuV4ZCM-0',
    appId: '1:294403375544:web:5f110000f372807f378f4d',
    messagingSenderId: '294403375544',
    projectId: 'snapsign2-0',
    authDomain: 'snapsign2-0.firebaseapp.com',
    storageBucket: 'snapsign2-0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe-pk27oNzXwQ16HJ-Z42DbInLdT5WhxY',
    appId: '1:294403375544:android:eb9c53ee3b4ae00a378f4d',
    messagingSenderId: '294403375544',
    projectId: 'snapsign2-0',
    storageBucket: 'snapsign2-0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdLS2ZWzO-DffX0JjTwmEe0sYeUESCuTg',
    appId: '1:294403375544:ios:10730edf2ce3214c378f4d',
    messagingSenderId: '294403375544',
    projectId: 'snapsign2-0',
    storageBucket: 'snapsign2-0.appspot.com',
    iosClientId: '294403375544-lu1suvprmra5n41ks0vmpu673nbtkdoi.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSnapsign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdLS2ZWzO-DffX0JjTwmEe0sYeUESCuTg',
    appId: '1:294403375544:ios:10730edf2ce3214c378f4d',
    messagingSenderId: '294403375544',
    projectId: 'snapsign2-0',
    storageBucket: 'snapsign2-0.appspot.com',
    iosClientId: '294403375544-lu1suvprmra5n41ks0vmpu673nbtkdoi.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSnapsign',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcZLKLC3g7fEvTd2R8HW4niPvuV4ZCM-0',
    appId: '1:294403375544:web:777c2f9ce5474def378f4d',
    messagingSenderId: '294403375544',
    projectId: 'snapsign2-0',
    authDomain: 'snapsign2-0.firebaseapp.com',
    storageBucket: 'snapsign2-0.appspot.com',
  );

}